name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - FrugalGuy
body:
  - type: markdown
    attributes:
      value: |
         * Before reporting a new issue please check and search in List of existing issues |
         * Please check Online Documentation |
         * Take a look at the Troubleshooting guide |
         * If still experiencing the issue, please provide as many details as possible below about your hardware, computer setup and code.
  - type: input
    id: board
    attributes:
      label: "Board"
      description: "On which board does this issue occur?"
      placeholder: "e.g., ESP32 Dev Module, ESP32-S2, ..."
    validations:
        required: true
  - type: textarea
    id: "what-happened"
    attributes:
      label: "Device Description?"
      description: "What development board or other hardware is the chip attached to?"
      value: "e.g., DevKit A, plain module on breadboard, etc. If custom or unusual, please attach a photo."
    validations:
      required: true

  
